version: '3'

services:
  postgres:
    image: 'postgres:14.4'
    container_name: 'java-postgres-pract'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=web'
    ports:
      - "5432:5432"

  app:
    build: ./
    container_name: 'java-app-pract'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/web
    ports:
      - "8080:8080"
    links:
      - postgres
    depends_on:
      - postgres